project 'OpenCai.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'OpenCai' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for OpenCai
pod 'AFNetworking'
pod 'SDWebImage'

  target 'OpenCaiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenCaiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
